export const alphabets = [
  { id: "01", value: "Nauseous" },
  { id: "02", value: "Dilate" },
  { id: "03", value: "Indict" },
  { id: "04", value: "Liquefy" },
  { id: "05", value: "Wednesday" },
  { id: "06", value: "Sherbet" },
  { id: "07", value: "Bologna" },
  { id: "08", value: "Playwright" },
  { id: "09", value: "Fuchsia" },
  { id: "10", value: "Minuscule" },
  { id: "11", value: "Ingenious" },
  { id: "12", value: "Sacrilegious" },
  { id: "13", value: "Accommodate" },
  { id: "14", value: "Orangutan" },
  { id: "15", value: "Mischievous" },
  { id: "16", value: "Gubernatorial" },
  { id: "17", value: "Acquiesce" },
  { id: "18", value: "Conscientious" },
  { id: "19", value: "Paraphernalia" },
  { id: "20", value: "Onomatopoeia" },
];
const alpha = [
  "Nauseous",
  "Dilate",
  "Indict",
  "Liquefy",
  "Wednesday",
  "Sherbet",
  "Bologna",
  "Playwright",
  "Fuchsia",
  "Minuscule",
  "Ingenious",
  "Sacrilegious",
  "Accommodate",
  "Orangutan",
  "Mischievous",
  "Gubernatorial",
  "Acquiesce",
  "Conscientious",
  "Paraphernalia",
  "Onomatopoeia",
];
export default alpha;
